# Generated by Django 3.1.12 on 2021-08-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_remove_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='class_name',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(default=''),
        ),
    ]
